//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TkaHuXakaccuu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Покупка
    {
        public int ID { get; set; }
        public Nullable<int> Фурнитура { get; set; }
        public Nullable<int> Ткань { get; set; }
        public Nullable<int> Услуга { get; set; }
        public Nullable<int> Клиент { get; set; }
        public Nullable<double> Количество { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Ткани Ткани { get; set; }
        public virtual Услуги Услуги { get; set; }
        public virtual Фурнитура Фурнитура1 { get; set; }
    }
}
