//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TkaHuXakaccuu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ткани
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ткани()
        {
            this.ЗаказТкани = new HashSet<ЗаказТкани>();
        }
    
        public int ID { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> ВидТкани { get; set; }
        public Nullable<int> Материал { get; set; }
        public Nullable<double> Количество { get; set; }
        public Nullable<double> ДлинаВРулоне { get; set; }
        public Nullable<double> Ширина { get; set; }
        public Nullable<double> Плотность { get; set; }
        public Nullable<int> Производитель { get; set; }
        public Nullable<double> Цена { get; set; }
        public Nullable<double> Скидка { get; set; }
        public byte[] Фото { get; set; }
    
        public virtual ВидыТканей ВидыТканей { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЗаказТкани> ЗаказТкани { get; set; }
        public virtual Материалы Материалы { get; set; }
        public virtual Производители Производители { get; set; }
    }
}
