//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TkaHuXakaccuu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Фурнитура
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Фурнитура()
        {
            this.Покупка = new HashSet<Покупка>();
        }
    
        public int ID { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> ВидФурнитуры { get; set; }
        public Nullable<int> ЕдИзмерения { get; set; }
        public Nullable<int> Производитель { get; set; }
        public Nullable<double> Цена { get; set; }
        public Nullable<double> Количество { get; set; }
        public Nullable<double> Скидка { get; set; }
        public byte[] Фото { get; set; }
    
        public virtual ВидФурнитуры ВидФурнитуры1 { get; set; }
        public virtual ЕдИзмерения ЕдИзмерения1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Покупка> Покупка { get; set; }
        public virtual Производители Производители { get; set; }
    }
}
